common: &common
  adapter: postgresql
  username: sampleapp
  password: sampleapp # from psql setup, see Postgresql

development:
  <<: *common
  database: sampleapp_development

test:
  <<: *common
  database: sampleapp_test

production:
  <<: *common
  database: sampleapp_production